# Setup
title:               Seokjun Choi
tagline:             ''
description:         'Menu'
url:                 https://letsjdosth.github.io/
baseurl:             ''
paginate:            1
permalink:           pretty

# About/contact
author:
  name:              Seokjun Choi
  url:               
  email:             schoi90@ucsc.edu

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
